apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ./nginx/deployment.yaml
  - ./nginx/service.yaml
patches:
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      spec:
        replicas: 2
